### ISSUE TITLE
Amazon Pay support

### ISSUE THREAD

**Issue by christianzichichi** [Adyen/adyen-salesforce-commerce-cloud#542] opened 2021-09-06 09:53 UTC
**Is your feature request related to a problem? Please describe.**
Amazon Pay is not available in the cartridge as payment method and express checkout option

**Describe the solution you'd like**
Amazon Pay available in the cartridge as payment method and express checkout option

**Additional context**
I can see there is work being done on the develop branch regarding Amazon Pay as payment method: https://github.com/Adyen/adyen-salesforce-commerce-cloud/commit/2cd91e97ec22b791d67e38cb3c53ad5d5197e498

Is there an official release date for 1. Amazon Pay as payment method 2. Amazon pay as express checkout option?

Thanks
Best

Christian

**Comment by maassenbas** [comment] 2021-09-06 11:41
Hi @christianzichichi ,
Amazon Pay as payment method will be available in the upcoming release (version 21.2.0). 
We are currently in a testing phase and will start the release shortly after. 

As this enhancement is a duplicate of [this](https://github.com/Adyen/adyen-salesforce-commerce-cloud/issues/478), I will close this one. 

Kind regards,
Bas Maassen
Adyen

**Closed by maassenbas** 2021-09-06 11:41 UTC
Labels: enhancement
