### ISSUE TITLE
Paypal express total amount

### ISSUE THREAD

**Issue by AVATOR** [Adyen/adyen-salesforce-commerce-cloud#1143] opened 2024-08-15 08:37 UTC
**Describe the bug**
Please revert with changes because the service sends an incorrect price because the EMEA tax includes the amount.
https://github.com/Adyen/adyen-salesforce-commerce-cloud/commit/4da8a1d3392dd33e94a5581fc5db028ec1a249e6#diff-830b5a27595728821d76d27db04329d8cbeaf9ca4f83be76ba30fa4b49e08d42R19

<img width="1311" alt="image" src="https://github.com/user-attachments/assets/05228a3e-9db0-4078-beac-d59e352e0456">

**Comment by zenit2001** [comment] 2024-08-15 11:31
Hi @AVATOR ,

Thanks for reaching out to us.
We tried reproducing the reported issue using the latest version of the plugin (v24.3.2), however we can't reproduce it.

Can you please open a support ticket with Adyen, including the details for the use case?
In case the issue comes from a plugin perspective, the support team will reach out to us and we will take care of the problem.

With kind regards,
Zenit
Adyen

**Comment by zenit2001** [comment] 2024-09-19 09:16
Hey @AVATOR ,

I am closing this issue since it is not reproducible.
If the issue is persistent on your end, you can reach out to our support team.

Kind regards,
Zenit
Adyen

**Closed by zenit2001** 2024-09-19 09:16 UTC
