### ISSUE TITLE
Error: invalid path [Windows]

### ISSUE THREAD

**Issue by gokaygurcan** [Adyen/adyen-salesforce-commerce-cloud#602] opened 2021-12-16 13:20 UTC
**Describe the bug**
Looks like the `*` character in the path causes an error on Windows machines. Specifically this one: [https://github.com/Adyen/adyen-salesforce-commerce-cloud/tree/main/jest/__mocks__/*](https://github.com/Adyen/adyen-salesforce-commerce-cloud/tree/main/jest/__mocks__/*)

**To Reproduce**
Checkout the repository on a Windows machine and see the error.

**Expected behavior**
Checking out the code as usual and not seeing any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/1509413/146378846-b56274d0-c5b7-44d6-a2f7-60cb1d10e191.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
This is a request coming from an external party, I can't reproduce since I don't use Windows myself.

**Comment by wboereboom** [comment] 2021-12-16 14:05
Hi @gokaygurcan,

Thanks for raising this issue.
This is actually a duplicate of SalesforceCommerceCloud/link_adyen#72
and has been fixed in #599, which will be included in our next release.

Kind regards,
Wouter
Adyen

**Closed by wboereboom** 2021-12-16 14:05 UTC
Labels: duplicate

**Comment by gokaygurcan** [comment] 2021-12-16 15:56
Fingers crossed, I guess.
