### ISSUE TITLE
Missing "modal-content" Wrapper Causing Bootstrap Modal Display Issue

### ISSUE THREAD

**Issue by s4ty** [Adyen/adyen-salesforce-commerce-cloud#1029] opened 2023-12-20 07:55 UTC
**Describe the bug**
We have integrated the Adyen Cartridge for our SFCC Shop to handle payments. However, upon closer inspection, it appears that the modal window functionality is not working correctly. After thorough analysis, we have identified that a crucial wrapper, "modal-content," necessary for Bootstrap Modal, is missing. This absence is causing the display to malfunction.

int_adyen_SFRA/cartridge/templates/default/adyenActionModal.isml

**To Reproduce**
1. Click "Place Order" (Last Checkout Step)

**Expected behavior**
The modal window should display correctly with all relevant content and functionalities.

**Screenshots**
without wrapper
![modal-issue](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/1499134/a1a0bca8-aca9-4ea5-a7ec-670da9e7f6e8)
with wrapper
![modal-solution](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/1499134/ac197d4d-9456-4111-a339-d45f0675cca7)

**Additional context**
Since the Modal is Bootstrap based it should have to correct wrapper see:
https://getbootstrap.com/docs/4.0/components/modal/
or
https://getbootstrap.com/docs/5.0/components/modal/

**Comment by zenit2001** [comment] 2024-01-04 14:38
Hi @s4ty ,

Thanks for reaching out.
We are not able to reproduce the issue in our environments.
Could you please confirm that you haven't added customizations to our code, and provide us the version of the cartridge and SFRA version that you reproduced this issue?

With kind regards,
Zenit 
Adyen

**Comment by amihajlovski** [comment] 2024-01-12 12:27
Hello,

Closing this because its not relevant and not reproducible on a clean instance. 
Please try it without customizations and open a new issue if the problem persist.

Kind regards,
Aleksandar
Adyen

**Closed by amihajlovski** 2024-01-12 12:27 UTC

**Comment by s4ty** [comment] 2024-10-17 10:15
Hi @Zenit, @amihajlovski,

Thank you for your responses.

I would like to clarify that, according to the official Bootstrap documentation, the <div class="modal-content"> wrapper is indeed required for proper modal functionality. The standard structure for a Bootstrap modal includes this wrapper, as shown here:

```
Copy code
<div class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <!-- Header content -->
      </div>
      <div class="modal-body">
        <!-- Body content -->
      </div>
      <div class="modal-footer">
        <!-- Footer content -->
      </div>
    </div>
  </div>
</div>
```
The absence of this modal-content div causes display issues because Bootstrap relies on this wrapper for proper styling and functionality of the modal window. If this wrapper is missing, the modal may not behave as expected.

While it may not be reproducible in a clean instance, this missing wrapper can lead to issues when integrating with other parts of the system or when customizing the UI. I believe it would be beneficial to review whether this wrapper should be included to ensure compatibility with Bootstrap standards.
